In [1]:
import numpy as np

In [2]:
a = np.arange(6)
print(f"The array shape is: {a.shape}")
print(a)

The array shape is: (6,)
[0 1 2 3 4 5]


In [3]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])
print(f"The matrix shape is: {M.shape}")
print(M)

The matrix shape is: (2, 3)
[[1 2 3]
 [4 5 6]]


In [4]:
C = np.arange(24). reshape(2, 3, 4)
print(f"The shape of C is: {C.shape}")
print(C)

The shape of C is: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
a = np.arange(10)**3
print(a)
print(a[9])
print(a[2:5])
print(a[-1])
print(a[::-1])

[  0   1   8  27  64 125 216 343 512 729]
729
[ 8 27 64]
729
[729 512 343 216 125  64  27   8   1   0]


In [6]:
b = np.arange(20).reshape(5,4)
print(b)
print(b[2,3])
print(b[0:3, 1])
print(b[:, 2:4])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
11
[1 5 9]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]


In [7]:
data = np.array([1, 2, 3])
ones = np.ones(3, dtype=int)
print(data+ones)
print(data-ones)
print(data*ones)
print(data/ones)

[2 3 4]
[0 1 2]
[1 2 3]
[1. 2. 3.]


In [8]:
a = np.arange(10) ** 2
print(a)
print(np.sum(a))

[ 0  1  4  9 16 25 36 49 64 81]
285


In [9]:
b = np.array([[1, 1],
             [2, 2]])
print(np.sum(b, axis=0))
print(np.sum(b, axis=1))

[3 3]
[2 4]


In [10]:
X = np.arange(10)
print(X.mean())
print(X.std())

4.5
2.8722813232690143


In [11]:
print(X * 2.5)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [12]:
A = np.arange(0, 40, 10). reshape((4,1))
print(A)
B = np.array([0, 1, 2])
print(B)
C = A + B
print(C)

[[ 0]
 [10]
 [20]
 [30]]
[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [13]:
print(C.ravel()) # used for flattening

[ 0  1  2 10 11 12 20 21 22 30 31 32]


In [14]:
a = np.arange(6)
row = a[np.newaxis, :]
col = a[:, np.newaxis]
print(row.shape, col.shape)

(1, 6) (6, 1)


In [15]:
rng = np.random.default_rng(seed=42)
R = rng.random((3,3))
print(R)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]


In [16]:
rng = np.random.default_rng(seed=2026)
I = rng.integers(low=0, high=10, size=(4,5))
print(I)

[[8 1 0 6 3]
 [4 0 3 6 3]
 [8 7 7 9 7]
 [1 8 6 0 2]]


In [17]:
a = np.arange(12).reshape(3,4)
mask = a > 4
print(mask)
selected = a[mask]
print(selected)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]


In [18]:
a = np.arange(10) ** 2
i = np.array([1, 1, 2, 4, 6])
print(a[i])

[ 1  1  4 16 36]


In [19]:
a = np.arange(6)
b = np.arange(6, 10)
c = np.concatenate((a, b))
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
X = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6]])
Z = np.concatenate((X, y), axis=0)
print(Z)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
n = np.array([10, 40, 30, 20, 50])
print(np.sort(n))

[10 20 30 40 50]


In [22]:
D = np.arange(24).reshape((3,2,4))
print(D)
print(D.ndim)
print(D.size)
print(D.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
3
24
(3, 2, 4)
